apiVersion: v1
kind: Service
metadata:
  name: benedict-svc
  labels:
    component: elasticsearch
    role: data
spec:
  type: LoadBalancer
  ports:
  - port: 9300
    name: transport
  - port: 9200
    name: http
  selector:
    name: es
