apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-deploy
  labels:
    name: es-deploy
    component: elasticsearch
spec:
  selector:
    matchLabels:
      name: es
  replicas: 1
  template:
    metadata:
      labels:
        name: es
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
          ports:
            - containerPort: 9200
              name: db
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
