apiVersion: v1
kind: Service
metadata:
  name: es-svc
  labels:
    name: es-svc
    component: elasticsearch
spec:
  type: LoadBalancer
  ports:
  - port: 9300
    name: transport
  - port: 9200
    name: http
  selector:
    name: es
