apiVersion: apps/v1
kind: Deployment
metadata:
  name: muffin-deploy
  labels:
    name: muffin-deploy
    component: boot
spec:
  selector:
    matchLabels:
      name: muffin
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        name: muffin
    spec:
      containers:
        - name: muffin
          image: "asia.gcr.io/hardy-baton-254603/muffin:0.0.1"
          ports:
            - containerPort: 8081
          env:
            - name: "JAVA_OPTS"
              value: "-Delasticsearch.host=elasticsearch-data"
