apiVersion: v1
kind: Service
metadata:
  name: poachedeggs-svc
  labels:
    name: poachedeggs-svc
    component: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
  selector:
    name: poachedeggs
