version: '3'
services:
  benedict-retriever-app:
    image: 'benedict-retriever-app:latest'
    ports:
      - 8081:8081
    networks:
      - esnet
    depends_on:
      - elasticsearch
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.8.2'
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_dir:/usr/share/elasticsearch/data
    networks:
      - esnet
  kibana:
    image: 'docker.elastic.co/kibana/kibana:6.8.2'
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - elasticsearch
volumes:
  es_dir:
    driver: local
networks:
  esnet: